[versions]
junit5 = "6.0.1"
junit4 = "4.13.2"
kotlin = "2.2.21"
intellijPlatform = "2.10.5"
kover = "0.9.3"
communityVersion = "2025.1"
mockk = "1.14.6"

[libraries]
junit5Api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5Engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }