[versions]
junit5 = "5.11.4"
junit4 = "4.13.2"
mockito = "5.14.2"
jmh = "1.37"
kotlin = "2.1.10"
intellijPlatform = "2.6.0"
kover = "0.9.1"
jmhPlugin = "0.7.3"
communityVersion = "2024.3"

[libraries]
junit5Api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5Engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
jmhCore = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmhAnnprocessor = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }